#! /usr/bin/bash
ren() {
if [[ $* =~ ^[:-] ]]
then
s=$*;o=
[[ $1 =~ ^- ]]	&&(s=$2;o=$1)
s=${s:1}
[[ $s =~ ' :' ]] ||{ echo Put in the other ':' as marker for regex replacement pattern;return; }
a=${s% :*};a=${a%% }
b=${s#* :}
# converting PCRE to GNU-extended regex
x=`echo $a |sed -r 's/\[\^?..+?-[^]]*\]/./g; s/(\[.*?)\\\w([^]]*\])/\1a-z0-9\2/g; s/(\[.*?)\\\d([^]]*\])/\10-9\2/g ;s/\\\d/[0-9]/g'`
echo GNU-ext regex:  $x
# The RHS below after '$' char if Linux: \n, if ported on Windows/Msys2: \r\n if ported on Mac: \r
IFS=$'\n'
if [[ ${a##'('} =~ ^/ ]]
then
	# s is the first longest literal
	s=`echo $x |sed -r 's/([^[|*+\\{.]+).*/\1/ ;s/[()]//g'`
	for l in `find ${s%/*} -noleaf -regextype posix-extended -iregex "$x" | gre -ie "${a/'/'/'\/'}"`
	{
	mv $o -vS _old $l `echo $l | sed -r "s~$x~$b~i"`
	}
else
	for l in `find ~+ -noleaf -regextype posix-extended -iregex "$PWD/${x}" | gre -ie "$a"`
	{
	mv $o -vS _old $l `echo $l | sed -r "s~$x~$b~i"`
	}
fi
elif test $1 ;then mv -vbS _old $*
fi;}
